#include <iostream>
using namespace std;
int main()
{
	try{
	
		return 0;
	}
	catch (_exception& e) {

	}
	catch (...) {

		return 1;
	}
}